#! /usr/bin/sh

# AUTOSTART
xsetroot -cursor_name left_ptr & # default cursor
udiskie & # usb mounting
sxhkd & # keybindings
#caffeine &
bg=$(xgetres background)
fg=$(xgetres foreground)
dunst -lb "$bg" -nb "$bg" -cb "$bg" -lf "$fg" -bf "$fg" -cf "$fg" -nf "$fg" -frame_color "$fg" &
$HOME/.config/polybar/launch.sh & # polybar
syncthing & # file syncing

# MONITOR
if [[ "$(hostname)" == 'mihranLaptop' ]]; then
  picom -bfc # compositor

  bspc monitor $(bspc query --monitors | head) -d 0 1 2 3 4 5 6 7 8 9
  # WALLPAPER (chosen randomly at startup)
  ~/scripts/random-wallpaper
  # LightDM Lockscreen
  light-locker --lock-on-suspend &
  bspc config top_padding 20
elif [[ "$(hostname)" == 'mihranDesktop' ]]; then
  picom --experimental-backends -bfc # compositor
  # Primary display settings
  xrandr --output DisplayPort-0 --primary --mode 1920x1080 --rate 144
  bspc monitor DisplayPort-0 -d 0 1 2 3 4
  bspc monitor HDMI-A-0 -d 5 6 7 8 9
  # WALLPAPER (chosen randomly at startup)
  ~/scripts/random-wallpaper
  # LightDM Lockscreen
  light-locker --lock-on-suspend &
  # PulseAudio + JACK Server
  pavucontrol &
  # OpenRGB
  $HOME/scripts/openrgb_startup &

  bspc config top_padding 40
  # Open discord
  discord &

  # GameStream
  xrandr --newmode "1368x768_60.00"   85.25  1368 1440 1576 1784  768 771 781 798 -hsync +vsync
  xrandr --addmode DisplayPort-0 1368x768_60.00
  sudo -u mihranmashhud sunshine ~/.config/sunshine/sunshine.conf &

  # Replay Buffer
  obs --startreplaybuffer --minimize-to-tray &
fi


# BSPWM configuration
bspc config border_width         2
bspc config window_gap           8
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       any
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# BSPWM colors
bspc config normal_border_color "$(xgetres darkgrey)"
bspc config focused_border_color "$(xgetres blue)"
bspc config presel_feedback_color "$(xgetres darkgrey)"

# Rules
[ -f ~/.config/bspwm/rules ] && source ~/.config/bspwm/rules
