#!/usr/bin/bash

set -e

DEVICES=`nmcli device show | grep GENERAL.DEVICE | sed 's/ *//g' | cut -d: -f2`

for DEV in $DEVICES; do
  if [[ "$DEV" != "$1" ]]; then
    echo "Disabling $DEV"
    sudo ip link set "$DEV" down
  else
    echo "Enabling $DEV"
    sudo ip link set "$DEV" up
  fi
done
